labels:
  - name: "feature"
    color: "0066ff"
    description: "Feature or enhancement."
  - name: "bug"
    color: "d73a4a"
    description: "Bug report"
  - name: "design"
    color: "e91e63"
    description: "Design work or discussion"
  - name: "ui"
    color: "7c3aed"
    description: "User interface"
  - name: "database"
    color: "10b981"
    description: "Database-related"
  - name: "auth"
    color: "f59e0b"
    description: "Authentication/authorization"
  - name: "github"
    color: "24292e"
    description: "GitHub-related"
  - name: "ai"
    color: "8b5cf6"
    description: "AI/ML work"
  - name: "setup"
    color: "64748b"
    description: "Repository setup / tooling"
  - name: "P0: Critical"
    color: "dc2626"
    description: "Priority 0 - Critical"
  - name: "P1: High"
    color: "f59e0b"
    description: "Priority 1 - High"
  - name: "P2: Medium"
    color: "3b82f6"
    description: "Priority 2 - Medium"
  - name: "P3: Low"
    color: "6b7280"
    description: "Priority 3 - Low"
