import type { Config } from "tailwindcss"

const config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c2c6d6",
        "tertiary-fixed-dim": "#4de082",
        "surface-bright": "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "on-primary-container": "#fefcff",
        "surface-tint": "#0053db",
        outline: "#727785",
        "on-tertiary-container": "#f6fff3",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "on-surface": "#191c1e",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#005227",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary": "#ffffff",
        "primary-container": "#1e40af",
        "on-tertiary-fixed": "#00210c",
        secondary: "#565e74",
        "on-primary-fixed": "#00174b",
        primary: "#2563EB",
        "tertiary-container": "#008644",
        "secondary-fixed": "#dae2fd",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface-container-high": "#e6e8ea",
        tertiary: "#006a34",
        "tertiary-fixed": "#6dfe9c",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2d3133",
        error: "#ba1a1a",
        "surface-container-low": "#f2f4f6",
        "on-background": "#191c1e",
        "on-secondary-container": "#5c647a",
        "on-surface-variant": "#424754",
        "surface-container": "#eceef0",
        "secondary-fixed-dim": "#bec6e0",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed": "#131b2e",
        "on-secondary": "#ffffff",
        background: "#f7f9fb",
        "inverse-primary": "#b4c5ff",
        surface: "#f7f9fb",
        "secondary-container": "#dae2fd",
        "surface-dim": "#d8dadc",
        "surface-container-highest": "#e0e3e5",
        "on-error-container": "#93000a",
        "primary-fixed": "#dbe1ff",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
} satisfies Config

export default config
